#!/bin/bash

# all inputs to cluster provisioning are here.  You need to edit this file to your liking.

# the userid that we should use when setting up the cluster
# USER=mpiuser
USER=hadoop

# the type of the cluster that we need to spin up 
# there needs to be a subdir for each of these types with scripts that are specific to this type of cluster
CLUSTER_TYPE=hadoopv1

# the key that we should use.  Note that this key will be generated added to SoftLayer.  Make sure that it does not exist
# in SoftLayer beforehand. 
KEYNAME=sshclusterkey3

# which file will contain the list of the master node  -- hostnames and ips ?
MASTERNODE_FILENAME=master.txt

# which file will contain the list of the master node -- hostname only ?
MASTERNODE_FILENAME_HOSTS=master

# which file will contain the list of slaves node[s] with hostnames and ips?
SLAVENODE_FILENAME=slaves.txt

# which file will contain the list of slaves node[s] with only hostnames ?
SLAVENODE_FILENAME_HOSTS=slaves

# this will be the hostname for the master node of the cluster
# please don't change this yet -- "master" is hard coded in hadoop conf files
# and is not updating yet :)
MASTER_HOSTNAME=master

# this will be the hostname for the slave nodes of the cluster
SLAVES_BASE_HOSTNAME=slaves

# the domain name for the cluster
DOMAIN=bdclass.com

# how many slaves do i need to provision?
NUM_SLAVES=4

#change this as needed. This is Hong Kong 02
#DATACENTER=hkg02
# DATACENTER=lon02
DATACENTER=sjc01

MASTER_CPU=8
MASTER_MEM=16384
MASTER_DISK=100
# please don't change this as apt-get is used to install software 
MASTER_OS=UBUNTU_14_64

SLAVE_CPU=4
SLAVE_MEM=8192
SLAVE_DISK=100
# please don't change this as apt-get ins used to install softwre
SLAVE_OS=UBUNTU_14_64



# TODO change this accordingly
# MASTER_IP=10.104.15.22

MASTER_NIC=1000
SLAVE_NIC=1000

